# Site 网站
title: 南
subtitle: ""
description: 只是一个备忘录, 用来记录一些我认为有用的东西
author: 南
language: zh-CN
timezone: ""

# 文章
post_asset_folder: true

# 扩展
theme: redefine

# 插件
markdown:
  preset: "default"
  render:
    html: true
    xhtmlOut: false
    langPrefix: "language-"
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 1
    collisionSuffix: ""
    permalink: false
    permalinkClass: "header-anchor"
    permalinkSide: "left"
    permalinkSymbol: "¶"
    case: 0
    separator: "-"

# 打包
all_minifier: true
